import type { DomainAutofillSelectors } from "../../types";

export const COMMON_SELECTORS: DomainAutofillSelectors = {
  fieldCollector: {
    formFields: [
      'input[type="text"]:not([type="hidden"])',
      'input[type="email"]',
      'input[type="tel"]',
      'input[type="url"]',
      'input[type="number"]',
      'input[type="password"]',
      'input[type="search"]',
      'input[type="checkbox"]',
      'input[type="radio"]',
      'input[role="combobox"]',
      'input[aria-haspopup="listbox"]',
      'input[aria-expanded]',
      'button[aria-haspopup="listbox"]',
      'button[role="combobox"]',
      'input[data-automation-id*="prompt"]',
      "textarea",
      "select",
    ],
    labelContainers: [
      ".form-group",
      ".field",
      ".input-wrapper",
      ".select-shell",
      ".select__container",
      '[class*="question"]',
      '[data-automation-id*="formField"]',
      '[data-automation-id*="prompt"]',
      '[data-uxi-widget-type*="prompt"]',
    ],
    labelElements: [
      "label",
      "legend",
      ".label",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      '[data-automation-id="promptLabel"]',
      '[data-automation-id="fieldLabel"]',
    ],
    requiredIndicators: [
      ".required",
      ".asterisk",
      '[aria-label*="required"]',
      '[data-automation-id*="required"]',
    ],
    checkboxWrappers: [".checkbox__wrapper", '[role="checkbox"]'],
    checkboxGroupContainers: [
      "fieldset",
      '[role="group"]',
      '[data-automation-id*="formField"]',
      ".form-group",
      ".field",
      ".input-wrapper",
    ],
    checkboxOptionLabelSelectors: ["label", ".label", "span", '[data-automation-id="promptOption"]'],
  },
  reactSelect: {
    container: [
      ".select-shell",
      ".select__container",
      ".select",
      '[data-automation-id*="prompt"]',
      '[data-uxi-widget-type*="prompt"]',
      '[role="combobox"]',
    ],
    control: [
      ".select__control",
      '[data-automation-id*="prompt"]',
      '[data-automation-id*="field"]',
      'button[aria-haspopup="listbox"]',
      'button[role="combobox"]',
      '[role="combobox"]',
    ],
    menuList: [
      ".select__menu-list",
      ".select_menu-list",
      '[data-automation-id="activeListContainer"]',
      "[role=\"listbox\"]",
      "ul[role=\"listbox\"]",
    ],
    option: [
      ".select__option",
      '[role="option"]',
      '[data-automation-id="promptOption"]',
      '[data-automation-id="menuItem"]',
    ],
    input: [
      ".select__input",
      "[role=\"combobox\"]",
      "input[aria-haspopup=\"listbox\"]",
      "input[aria-expanded]",
      "input[data-automation-id*=\"prompt\"]",
      "input[aria-controls]",
      "input[aria-owns]",
    ],
    multiValueContainer: [".select__value-container--is-multi", "[aria-multiselectable=\"true\"]"],
  },
};
