import type { DomainAutofillSelectors } from "../../types";

export const WORKDAY_SELECTORS: DomainAutofillSelectors = {
  fieldCollector: {
    formFields: [
      'input[type="text"]:not([type="hidden"])',
      'input[type="email"]',
      'input[type="tel"]',
      'input[type="url"]',
      'input[type="number"]',
      'input[type="password"]',
      'input[type="search"]',
      'input[type="checkbox"]',
      'input[type="radio"]',
      'input[role="combobox"]',
      'input[aria-haspopup="listbox"]',
      'input[aria-expanded]',
      'button[aria-haspopup="listbox"]:not(#settingsSelectorButton)',
      'button[role="combobox"]:not(#settingsSelectorButton)',
      'input[data-uxi-widget-type="selectinput"]',
      'input[data-uxi-element-id^="selectinput-"]',
      'input[data-automation-id*="prompt"]',
      "textarea",
      "select",
    ],
    labelContainers: [
      '[data-automation-id*="formField"]',
      '[data-automation-id*="prompt"]',
      '[data-uxi-widget-type*="prompt"]',
      ".form-group",
      ".field",
      ".input-wrapper",
    ],
    labelElements: [
      "label",
      "legend",
      ".label",
      '[data-automation-id="promptLabel"]',
      '[data-automation-id="fieldLabel"]',
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
    ],
    requiredIndicators: [
      '[aria-required="true"]',
      ".required",
      ".asterisk",
      '[data-automation-id*="required"]',
    ],
    checkboxWrappers: [".checkbox__wrapper", '[role="checkbox"]'],
    checkboxGroupContainers: [
      "fieldset",
      '[role="group"]',
      '[data-automation-id*="formField"]',
      ".form-group",
      ".field",
      ".input-wrapper",
    ],
    checkboxOptionLabelSelectors: [
      "label",
      ".label",
      "span",
      '[data-automation-id="promptOption"]',
      '[data-automation-id="menuItem"]',
    ],
  },
  reactSelect: {
    container: [
      '[data-automation-id*="prompt"]',
      '[data-uxi-widget-type*="prompt"]',
      '[data-automation-id="responsiveMonikerPrompt"]',
      '[data-uxi-widget-type="multiselectlist"]',
      '[role="combobox"]',
    ],
    control: [
      '[data-automation-id*="prompt"]',
      '[data-uxi-widget-type*="prompt"]',
      '[data-uxi-widget-type="selectinput"]',
      'input[data-uxi-widget-type="selectinput"]',
      'input[data-uxi-element-id^="selectinput-"]',
      'button[aria-haspopup="listbox"]',
      'button[role="combobox"]',
      '[role="combobox"]',
    ],
    menuList: [
      '[data-automation-id="activeListContainer"]',
      "[role=\"listbox\"]",
      "ul[role=\"listbox\"]",
    ],
    option: [
      '[data-automation-id="menuItem"]',
      '[data-automation-id="promptOption"]',
      '[data-automation-id="promptLeafNode"]',
      '[role="option"]',
    ],
    input: [
      'input[data-uxi-widget-type="selectinput"]',
      'input[data-uxi-element-id^="selectinput-"]',
      "[role=\"combobox\"]",
      "input[aria-haspopup=\"listbox\"]",
      "input[aria-expanded]",
      "input[aria-controls]",
      "input[aria-owns]",
    ],
    multiValueContainer: [
      "[aria-multiselectable=\"true\"]",
      '[data-automation-id="multiSelectContainer"]',
      '[data-uxi-widget-type="multiselect"]',
    ],
  },
};
